version: "3.7"
services:
  postgres:
    image: postgres:11-alpine
    environment:
      POSTGRES_PASSWORD: docker
    ports:
      - 5433:5432
    volumes:
      - $HOME/docker/volumes/postgres:/var/lib/postgresql/data
